# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
  apt:
    packages:
    - python-tk
    - python-lxml
    - python-tornado
    - python-tables

language: python
python: 3.6


env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=NEURON:7.4
    - OMV_ENGINE=NEURON:7.6
    #- OMV_ENGINE=PyNEURON
    - OMV_ENGINE=jNeuroML_validate

install:
    
    # Install OMV
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install numpy scipy # Why is this needed? Scipy doesn't seem to get installed correctly on trusty with addons above...
    - pip install tables # Ditto
    - pip install matplotlib # This is more because Matplotlib v2.x is required...
    
    # Install Allen SDK
    - pip install allensdk
    
    # See comment in CellTypesDatabase/models/483108201/.test.483108201.nrn.omt_ 
    
    # Need to pre install NEURON so nrnivmodl can be run targeting mod files in a different directory
    - omv install NEURON
    #- cd CellTypesDatabase/models/483108201
    #- /home/travis/neuron/nrn/x86_64/bin/nrnivmodl modfiles
    #- cd -


script:

    - omv all -V
    - omv list-engines -V
    

    
    
